[theme]
theme = "bad-wolf"
[icons]
icons = "material-nf"


# [[block]]
# block = "pomodoro"
# notify_cmd = "notify-send '{msg}'"
# blocking_cmd = false
# [block.theme_overrides]
# idle_bg="#121212"

[[block]]
block = "cpu"
interval = 1
format="$icon {$utilization} {$frequency} "
[block.theme_overrides]
idle_bg="#FF4C29"

[[block]]
block = "nvidia_gpu"
[block.theme_overrides]
idle_bg="#76B900"
good_bg="#76B900"
warning_bg="#76B900"

[[block]]
block = "memory"
format = " {$mem_used}/{$mem_total} ({$mem_used_percents}) "
interval = 5
warning_mem = 80
critical_mem = 95
critical_swap = 95
[block.theme_overrides]
idle_bg="#2C394B"


[[block]]
block = "sound"
step_width = 1
# on_click = "pactl set-sink-mute"
[block.theme_overrides]
idle_bg="#082032"

[[block]]
block = "time"
# interval = 1
# format = "%a %d/%m %R"
[block.format]
full = " $icon $timestamp.datetime(f:'%Y-%m-%d %R', l:fr_BE) "
short = " $icon $timestamp.datetime(f:%R) "
[block.theme_overrides]
#idle_bg="#222222"
idle_fg="#FC997C"

