[theme]
theme = "bad-wolf"
[icons]
icons = "material-nf"


# [[block]]
# block = "pomodoro"
# notify_cmd = "notify-send '{msg}'"
# blocking_cmd = false
# [block.theme_overrides]
# idle_bg="#121212"

[[block]]
block = "cpu"
interval = 1
format="$icon {$utilization} {$frequency} "
[block.theme_overrides]
idle_bg="#FF4C29"


[[block]]
block = "memory"
format = " {$mem_used}/{$mem_total} ({$mem_used_percents}) "
interval = 5
warning_mem = 80
critical_mem = 95
critical_swap = 95
[block.theme_overrides]
idle_bg="#2C394B"

# first battery internal
[[block]]
block="battery"
interval = 5
device="BAT0"
# empty_threshold = 1
# full_threshold = 99
format = " INT $icon{$percentage|} {$time|} "
empty_format = " INT $icon{$percentage|} {$time|} "
charging_format = " INT $icon{$percentage|} {$time|} "
full_format = " INT $icon{$percentage|} {$time|} "

# second battery removable 
[[block]]
block="battery"
interval = 5
device="BAT1"
# empty_threshold = 1
# full_threshold = 99
format = " REM $icon{$percentage|} {$time|} "
empty_format = " REM $icon{$percentage|} {$time|} "
charging_format = " REM $icon{$percentage|} {$time|} "
full_format = " REM $icon{$percentage|} {$time|} "

[[block]]
block="backlight"
[block.theme_overrides]
idle_bg="#202939"

[[block]]
block="hueshift"
hue_shifter="gammastep"
[block.theme_overrides]
idle_bg="#ece81a"
idle_fg="#222ea1"

[[block]]
block = "sound"
step_width = 1
# on_click = "pactl set-sink-mute"
[block.theme_overrides]
idle_bg="#082032"

[[block]]
block = "time"
# interval = 1
# format = "%a %d/%m %R"
[block.format]
full = " $icon $timestamp.datetime(f:'%Y-%m-%d %R', l:fr_BE) "
short = " $icon $timestamp.datetime(f:%R) "
[block.theme_overrides]
#idle_bg="#222222"
idle_fg="#FC997C"

